# Use the official image as a parent image
FROM rabbitmq:3.7-management

# Expose: the necessary ports are exposed in the base image:
# EXPOSE 25672 4369 5671
# EXPOSE 15671 15672

# Copy the config and queue definitions
#ADD rabbitmq.config /etc/rabbitmq/
#ADD definitions.json /etc/rabbitmq/
