FROM nginx:latest

# We install ping and curl for debugging purpose only!
# The resulting image is only 5M bigger.
RUN apt-get update && \
    apt-get install --no-install-recommends -y iputils-ping curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./nginx-flask-app-http.conf ./nginx-requestid.conf /etc/nginx/conf.d/

COPY ./nginx.conf /etc/nginx/
